export const SAVE_SHOP_TOKEN = 'SAVE_USER_CREDENTIALS'
export const CLEAR_SHOP_TOKEN = 'CLEAR_USER_CREDENTIALS'

export const RECEIVE_ALL_PAGES = 'RECEIVE_ALL_PAGES'

export const START_LOADING_PAGES = 'START_LOADING_PAGES'
export const FINISH_LOADING_PAGES = 'FINISH_LOADING_PAGES'
export const START_ACTIVATING_PAGE = 'START_ACTIVATING_PAGE'
export const FINISH_ACTIVATING_PAGE = 'FINISH_ACTIVATING_PAGE'
export const PAGE_BECOME_ACTIVE = 'PAGE_BECOME_ACTIVE'
export const START_DEACTIVATING_PAGE = 'START_DEACTIVATING_PAGE'
export const FINISH_DEACTIVATING_PAGE = 'FINISH_DEACTIVATING_PAGE'
export const PAGE_BECOME_INACTIVE = 'PAGE_BECOME_INACTIVE'

export const START_CHECKING_LOGIN_STATUS = 'START_CHECKING_LOGIN_STATUS'
export const FINISH_CHECKING_LOGIN_STATUS = 'FINISH_CHECKING_LOGIN_STATUS'

export const START_LOGIN = 'START_LOGIN'
export const FINISH_LOGIN = 'FINISH_LOGIN'

export const FINISH_LOADING_CUSTOMERS = 'FINISH_LOADING_CUSTOMERS'
export const RECEIVE_ALL_CUSTOMERS = 'RECEIVE_ALL_CUSTOMERS'
export const START_LOADING_CUSTOMERS = 'START_LOADING_CUSTOMERS'

export const FINISH_LOADING_CAMPAIGNS = 'FINISH_LOADING_CAMPAIGNS'
export const RECEIVE_ALL_CAMPAIGNS = 'RECEIVE_ALL_CAMPAIGNS'
export const START_LOADING_CAMPAIGNS = 'START_LOADING_CAMPAIGNS'

export const FINISH_LOADING_CUSTOMERS_GROUP = 'FINISH_LOADING_CUSTOMERS_GROUP'
export const RECEIVE_ALL_CUSTOMERS_GROUP = 'RECEIVE_ALL_CUSTOMERS_GROUP'
export const START_LOADING_CUSTOMERS_GROUP = 'START_LOADING_CUSTOMERS_GROUP'

export const SAVE_NEW_INBOX = 'SAVE_NEW_INBOX'
