export const SAVE_SHOP_TOKEN = 'SAVE_USER_CREDENTIALS'
export const CLEAR_SHOP_TOKEN = 'CLEAR_USER_CREDENTIALS'

export const RECEIVE_ALL_PAGES = 'RECEIVE_ALL_PAGES'

export const START_LOADING_PAGES = 'START_LOADING_PAGES'
export const FINISH_LOADING_PAGES = 'FINISH_LOADING_PAGES'

export const START_CHECKING_LOGIN_STATUS = 'START_CHECKING_LOGIN_STATUS'
export const FINISH_CHECKING_LOGIN_STATUS = 'FINISH_CHECKING_LOGIN_STATUS'

export const START_LOGIN = 'START_LOGIN'
export const FINISH_LOGIN = 'FINISH_LOGIN'
