export const FB_LOGIN_ENDPOINT = '/sessions/facebook'
export const MY_PAGES_ENDPOINT = '/pages'
export const ACTIVATE_PAGE_ENDPOINT = '/pages/pageId/subscribe'
export const CUSTOMERS_ENDPOINT = '/customers'
export const PAGE_MESSAGES_ENDPOINT = '/pages/pageId/messages'
export const CUSTOMER_GROUPS_ENDPOINT = '/customer-groups'
